# TensorFlow basics:

In [22]:
# Install once.
#!pip install tensorflow-gpu==1.13.1
# OR
# !pip install --user tensorflow-gpu

In [29]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow.compat.v1 as tf
import numpy as np


## Hello World!

In [32]:
hello = tf.constant("Hello World!")
tf.disable_eager_execution()
with tf.Session() as sess:
    print(sess.run(hello))

b'Hello World!'


## Creating tensors:

In [33]:
hello = tf.constant("Hello World!")                         # String.
const_scalar = tf.constant(7)                               # A scalar tensor.
const_matrix = tf.constant([[1,2], [3,4]])                  # A matrix tensor.
mat_fill = tf.fill((4,4),9)                                 # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))                                   # A 5x5 tensor filled with 1s.
mat_randn = tf.random_normal((3,3), mean=0, stddev=1.0)     # 3x3 random normal tensor.
mat_randu = tf.random_uniform((4,4), minval=0, maxval=1.0)  # 4x4 random uniform tensor.

In [34]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]
with tf.Session() as sess:
    for op in my_ops:
        res = sess.run(op)
        print(type(res))
        print('\n')
        print(res)
        print('\n')

<class 'bytes'>


b'Hello World!'


<class 'numpy.int32'>


7


<class 'numpy.ndarray'>


[[1 2]
 [3 4]]


<class 'numpy.ndarray'>


[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


<class 'numpy.ndarray'>


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<class 'numpy.ndarray'>


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<class 'numpy.ndarray'>


[[-1.6843772   0.4945933   1.2709894 ]
 [-0.5740204   0.43828887 -0.48445895]
 [-1.777321    1.0776471   1.253674  ]]


<class 'numpy.ndarray'>


[[0.42668772 0.3134569  0.71684754 0.11181629]
 [0.50303423 0.8494853  0.84914386 0.5995394 ]
 [0.6819701  0.5100572  0.27478218 0.3270527 ]
 [0.93374    0.6416371  0.27235174 0.41945064]]




## Math operations:

create two scalars ``n1`` and ``n2``  using ``tf.constant`` with any value of your choice and do the following operations: 
- **multplication** using ``tf.multiply`` and ``*``
- **addition** using ``tf.add`` and ``+``
- **pow** using ``tf.pow``

save each operation in a variable and run them using :

``
with tf.Session() as sess:
    sess.run(...)
    ...
``    

In [35]:
n1 = tf.constant(5)
n2 = tf.constant(2)
n3 = tf.multiply(n1,n2)
n4 = n1 * n2 
n5 = tf.add(n1,n2)
n6 = n1 = n2 
n7 = tf.pow(n1,2)
mylist = [n1,n2,n3,n4,n5,n6,n7]

In [36]:
with tf.Session() as sess:
    for op in mylist:
        res = sess.run(op)
        print(type(res))
        print('\n')
        print(res)
        print('\n')

<class 'numpy.int32'>


2


<class 'numpy.int32'>


2


<class 'numpy.int32'>


10


<class 'numpy.int32'>


10


<class 'numpy.int32'>


7


<class 'numpy.int32'>


2


<class 'numpy.int32'>


4




## Matrix functions and operations:

create two variables ``tf.constant([[1,2], [3,4]])`` and ``tf.constant([[5, 6], [7, 8]])``
then perfom ``tf.matmul`` and ``tf.multiply``.
- run them using session.run() (just like the previous example)
- conclude the difference between the two operations

perform also ``+`` , ``-`` , ``/`` , use round with the last operation with 3 decimal places after comma.

In [37]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[5, 6], [7, 8]])
c = tf.matmul(a,b)
d = tf.multiply(a,b)

In [39]:
mat_list = [a,b,c,d]
with tf.Session() as sess:
    for op in mat_list:
        res = sess.run(op)
        print(type(res))
        print('\n')
        print(res)
        print('\n')

<class 'numpy.ndarray'>


[[1 2]
 [3 4]]


<class 'numpy.ndarray'>


[[5 6]
 [7 8]]


<class 'numpy.ndarray'>


[[19 22]
 [43 50]]


<class 'numpy.ndarray'>


[[ 5 12]
 [21 32]]




here are some other operations you can do using constant variables

In [40]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.matrix_diag([1,2,3])
m_transpose = tf.matrix_transpose(m)
m_inverse = tf.matrix_inverse(m)
m_multiplied = tf.matmul(m, m_inverse)
m_determinant = tf.matrix_determinant(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]
with tf.Session() as sess:
    for mat in my_matrices:
        res = sess.run(mat)
        print(np.round(res,3))
        print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[ 1.  0.]
 [-0.  1.]]


-2.0




## TensorFlow Variable:

there are threee way to initialize your variables

In [41]:
# Initializing Variables #1
x = tf.Variable(initial_value=5, name='x')       # Define.
y = tf.Variable(initial_value=6, name='y')       # Define.
f = (x - y)*y + 3                                # Define.
sess = tf.Session()
sess.run(x.initializer)                          # Initialize.
sess.run(y.initializer)                          # Initialize. 
res = sess.run(f)  
print(res)
sess.close()

-3


In [50]:
# Initializing Variables #2
x = tf.Variable(initial_value=3, name='x')       # Define.
y = tf.Variable(initial_value=2, name='y')       # Define.
f = x*y + y + 3                                  # Define.
with tf.Session() as sess:
    x.initializer.run()                          # Initialize. The same as "sess.run(x.initializer)".
    y.initializer.run()                          # Initialize. The same as "sess.run(y.initializer)".
    res = f.eval()                               # The same as "res = sess.run(f)".
print(res)

11


the following initialization method is the widely used 

In [43]:
# Initializing Variables #3
x = tf.Variable(initial_value=7, name='x')       # Define.
y = tf.Variable(initial_value=3, name='y')       # Define.
f = x*y*y - y - 1                                # Define.
init = tf.global_variables_initializer()         # will go through all variables and initialize them 
with tf.Session() as sess:
    sess.run(init)                               # Initialize wil happen after running sess.run(init).
    res = f.eval()                               # The same as "res = sess.run(f)".
print(res)

59


- create ``my_tensor`` using tf.random_uniform of shape ``(4,4)`` of zero mean and 1 std
- create ``my_var`` using ``tf.Variable`` with an initial value ``my_tensor``
- run a global initializer using ``tf.global_variables_initializer`` and store it in ``init``
- start a session as usual and run ``init`` to initialize your variables 

In [48]:
my_tensor = tf.random_uniform((4,4))
my_var = tf.Variable(initial_value=my_tensor , name='my_var')
init = tf.global_variables_initializer()
with tf.Session() as sess : 
    sess.run(init)
print(sess.ramy_var)

<tf.Variable 'my_var_2:0' shape=(4, 4) dtype=float32>


## TensorFlow Placeholder

placeholders are different , they got initialized through run function using the ``feed_dict``.

**usage :** imagine a placeholder as booking a table at a restaurant ,in our case the guests are the input , you guessed it right **placeholders are used for input data** one cool property of placeholders is that you don't need to set number of observations
<br>

here's an example :

In [ ]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf.multiply(a, b)
with tf.Session() as sess:
    res = sess.run(y, feed_dict={a:2, b:3})           # Feed the actual valules.
    print(res)

In [ ]:
# Simulated data as NumPy array.
np.random.seed(123)
X1 = np.random.uniform(0.0, 1.0, (3,3))
X2 = np.random.normal(0.0, 1.0, (10,3))
b0 = np.array([1,2,3]).reshape((-1,1))
#
# The data may be a DataFrame.
# X1 = pd.DataFrame(X1)
# X2 = pd.DataFrame(X2)
#
X = tf.placeholder(tf.float32, shape=(None,3))       # "None" means that the number of rows is still undefined. 
b = tf.placeholder(tf.float32, shape=(3,1))
y = tf.matmul(X, b)
with tf.Session() as sess:
    print(sess.run(y, feed_dict={X:X1, b:b0}))       # Feed in the data.
    print("\n")
    print(sess.run(y, feed_dict={X:X2, b:b0}))       # Feed in the data.